version: '3.8'

services:
  tvt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tvt
    volumes:
      - .:/app
    working_dir: /app
    #entrypoint: bash -c "dos2unix /app/*.sh && /bin/bash -c \"./run.sh\""
    #command: ./run.sh
    entrypoint: bash -c "dos2unix /app/*.sh && bash -c 'while true; do echo \"[tvt] Container is up - $(date)\"; sleep 600; done'"
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
